### PR TITLE
Added a Plugin to search for a specific item in all the chests

### PR DESCRIPTION
**Pull request by Belkar**
I created a simple Plugin to search the World for a specific item in all the chests.
You start the plugin, a window opens and asks for the name of the item.
After you start the search a new window pops up with the coordinates of all found chests.

A neat addition would be to double click on the coordinate of a chest and the view would automatically focus the chest in the XNAView. I didn't want to destroy your architecture so I made no changes or tries there.

### CODE REVIEW

**Comment by enigmaquip** [comment]
Instead of a text input why not use a pre-populated pull down menu? The list is in the settings.xml, you could use the chest editor as an example for that

**Comment by SinisterStairs** [comment]
I actually like the text input... faster than waiting for the pulldown to cache and scrolling to the correct item.  :)  But for consistency sake, that would make sense.

**Comment by enigmaquip** [comment]
I just think you would get more consistent results..... and scrolling, you can type the first letter to jump to that section faster.
I would've used the Chest array instead of scrolling the entire map as well, but this is functional

**Comment by Belkar** [comment]
I copied the code of the "Open locked chests" plugin and modified it. And since this worked and I was to lazy to read through the whole source I didn't bother scrolling the entire map.
The text input has the advantage for example, that you can find both types of mirror if you search after "mirror". (And I didn't realize the option of the pull down menu)

This plugin was written in about an hour so there is still big room for improvements and additions.

**Comment by enigmaquip** [comment]
You've done a fine job. I don't know that any of us were working on a search chest plugin. I meant these as suggestions not criticisms

**Comment by Belkar** [comment]
Don't worry I took them as suggestions :). But I wanted to make my thoughts clear. I had fun working on this little project but currently don't have a lot of time to enhance it.

**Comment by SinisterStairs** [comment]
I'll probably modify the plugin (at least for my own use) so it can search the world too, to find gems or ores or wherever I misplaced my safe. :)

I started looking into how double-clicking could zoom to the location in the world, seems like it would be via CenterOnTile().

**Comment by BinaryConstruct** [comment]
Thanks for the contribution @Belkar

**Pull request merged**
