### PR TITLE
Change the type of {chest, dresser} or {sign, grave marker}.

### PR DESCRIPTION
**Pull request by CyberZHG**
Issue #472 

image

image

image

### CODE REVIEW

**Comment by CyberZHG** [comment]
Chests in 1.3

image

**Comment by SBlogic** [comment]
I like this and it works well, but some constructive criticism -- the Chests addition to settings.xml is redundant since chests are enumerated under <Tiles><Tiles ID="21"><Frames>...</Frames> already.  I'd suggest removing the Chests node and using the item frames so the chest data only needs to be updated in one place.

**Comment by CyberZHG** [comment]
Sign type could be changed now.

image

image

**Comment by CyberZHG** [comment]
Dressers are chests.

image

image

**Comment by TheHoodedTeddy13** [comment]
Good to know, thanks.

**Pull request closed without merging**
