### PR TITLE
Tools Revamp

### PR DESCRIPTION
**Pull request by enigmaquip**
Added fine control over what is being edited when using the edit tools. Tile brickstyle is not forced to use while editing a tile. Unlinked actuator and inactive, you can now make a tile inactive without having to leave an actuator on the tile. Draw multiple wires at once.
toolbar

### CODE REVIEW

**Comment by THEJaxster** [comment]
This is awesome, looking forward to the inactive tiles!  Will there be a tool (or way) to add actuators to sprites?  I currently just make the area for the sprites layout with actuated blocks then delete the blocks and place my sprite.  Thanks for making this awesome tool!!!

**Comment by enigmaquip** [comment]
All the Actuator/InActive tools look for is for a tile to be there, Sprites are tiles and so yes you would be able to place a sprite, then using the extras part of the drawing tool add actuators to them, or even make them InActive without placing the actuator on it first

**Comment by THEJaxster** [comment]
Thanks for the reply and answer @enigmaquip !!

**Comment by THEJaxster** [comment]
The Actuator tool does not work on sprites(tested on teleporter, chair, gemspark tiles(after placing)).  It works like it should when pasting tiles.  I'm using Windows 10 64bit , TEdit v3.6 19740.114 from Master on 8-15-15 ,  and .NET 4.51.  

noactuatoronsprite

Thanks again!

**Comment by enigmaquip** [comment]
While TEdit does not properly render actuators on sprites, nor inactive tiles, the info panel at the bottom will tell you if a tile has an actuator and/or is inactive

This was done with the code from this PR
actuator

**Comment by THEJaxster** [comment]
I have noticed that it doesn't render sometimes.  However, using the example above, it still did not put the actuators or inactive actuator on the sprites/tiles and does not show in the information pane below.  With my example, I tried without success.  I will try it again when the PR is published on the downloads page at ..binaryconstruct.com/downloads/  .  Again, thank you!  Paint the blocks is an awesome addition!

**Pull request merged**
