### PR TITLE
Paint!

### PR DESCRIPTION
**Pull request by enigmaquip**
Added ability to edit paint. Paint does render in pixelmap/minimap, but
not zoomed in full render

### CODE REVIEW

**Comment by ahamling27** [comment]
<3 <3 <3

This is just awesome! Keep up the great work fellas! Can't wait for the official release for 1.3! My adventure map is gonna be even better. :+1:

**Comment by BinaryConstruct** [comment]
Some cleanup is needed to merge this into the current version.

**Comment by enigmaquip** [comment]
Yea, I haven't had a chance to touch it since you've pushed all the updates

**Comment by BinaryConstruct** [comment]
I believe this has been merged with the other PR>

**Pull request closed without merging**
