### PR TITLE
Added Chinese language

### PR DESCRIPTION
**Pull request by bai1996**
Add Chinese language

### CODE REVIEW

**Comment by BinaryConstruct** [comment]
Thanks! I will get this in the next release.

**Comment by BinaryConstruct** [comment]
This is a model example of how to add a language, I'm going to post this to the wiki for future examples.

**Comment by bai1996** [comment]
有什么事吗？

**Comment by bai1996** [comment]
> 哥，你还在吗

有什么事吗？

**Comment by wdfcf222** [comment]
> 



> > 哥，你还在吗
> 
> 有什么事吗？

你是谁？

**Comment by bai1996** [comment]
> > 
> 
> > > 哥，你还在吗
> > 
> > 
> > 有什么事吗？
> 
> 你是谁？

什么意思？我就是个开发者啊，怎么了？

**Comment by Strynker** [comment]
Add the Spanish language, I can contribute.

**Comment by bai1996** [comment]
> Add the Spanish language, I can contribute.
[5.0.0-beta9](https://github.com/TEdit/Terraria-Map-Editor/releases/tag/5.0.0-beta9) is already supported Spanish language
[ Add Spanish es-ES Localization #1959 ](https://github.com/TEdit/Terraria-Map-Editor/pull/1959)

scratch one's head

**Pull request merged**
