### PR TITLE
1.3 Items/NPC

### PR DESCRIPTION
**Pull request by SBlogic**
Update to settings.xml (new items and new friendly NPC).  Tile and wall
data to follow later.

### CODE REVIEW

**Comment by SBlogic** [comment]
Fixed locally.  I'm currently working on walls and tiles, so the next PR I submit will address this.

**Comment by speeder** [comment]
Hey SBlogic, I am trying to do the map format file (since I saw you are working on this).

Any idea when you will finish the xml? I think I will be done with my part soon :) (I am asking because the editor don't handle gracefully this: it crashes when you zoom in somewhere with new tiles :( )

**Comment by SBlogic** [comment]
It's almost done except for tiles, which is a pretty big job.  I can add the new tiles tomorrow (Sunday) to at least get blocks added, but some sprites will still be missing until I can go back and fill in the items that already exist under other IDs (furniture, platforms, etc.)  I was able to test the XML against a 1.2.4.1 world in the latest source and it's working there.

Related, there's a missing tag terminator on one line in this PR (as noted above), and since it's not merged, attempting to submit my latest updates for walls refuses to work.  Is there a way I can remove this PR in order to submit something that works, or do I need to wait until this is merged or rejected?  (Will "Close" dump the submission?)

**Comment by speeder** [comment]
Hey, my part is finished I guess, I think you can merge my pull request against your fork (I have no idea how... I am a github newbie) and then you will be able to test your xml against 1.3 files.

**Comment by SBlogic** [comment]
I ran into some issues trying to test the tiles on a 1.2.4.1 in the old code, constant breaks on TileFrameImportant[], index out of range.  In order to work around this, I've copied @speeder 's fork and I'm now trying to finish the fine tuning in that copy.  I can now load and test against a proper 1.3 world at least, but I still have a few dozen IDs to work through and verify.  Progress!

Note:  If you turn uncheck "Show Textures" in the Display menu, you should be able to zoom in without crashing, but tiles are indicated as invalid.

**Comment by SBlogic** [comment]
Two new commits should flesh out the last of the issues with the new XML data (and fix a minor rendering issue with the NPCs).  This should be sufficiently friendly for a working 1.3-compatible version, but doesn't cover absolutely everything.  New items that place existing tile IDs (banners, furniture, chests, etc.) haven't been updated and are still missing from the sprite list.  I'll need to go through all 800 items line by line to fix this, and it's going to take some time.

**Comment by speeder** [comment]
Tested on my end, wonderful work! Stopped the bucket-tool related crashes too it seems :)

Now it is only a matter of polishing (for example adding the new 1.3 properties to the interface, something that is hard to do here, BinaryLogic made the interface using an editor that requires a paid version of Visual Studio...)

**Comment by SBlogic** [comment]
Huh, I updated the whole World Properties interface for 1.2.4 in the free Visual Studio, guess maybe I did it the hard way.  ;)  Ah well, I don't have a problem doing that for 1.3 as long as all the header fields are mapped out.

**Comment by speeder** [comment]
I actually DID updated it too (the hard way...), except for the kill counts, I tried to create a new tab, but ended accidentally overwriting my previously updated files :(

I can update it again, but I don't know how to make in the XAML a easy way to allow editing of the kill counts, if you have any ideas, it would be great.

**Comment by SBlogic** [comment]
The settings.xml should be complete now for all new 1.3 items (walls, tiles, sprites).  As noted in the commit, sinks are oddly framed, and I can't find a good way to make them work currently.  I inspected each new sprite, and they all seem to be rendering correctly and showing up with the correct names.

**Comment by SBlogic** [comment]
Finishing up the tally, now this is a thing:

Tally Preview

(Required a bit of XML enhancement, along with the UI.)

**Comment by TheHoodedTeddy13** [comment]
Wow. That is a long list.  Can you think of any way to sort them?  Like, maybe a dropdown menu of where you'd find them?  Or would that be too much?

**Comment by SBlogic** [comment]
It's mainly intended to just be informational, giving context to the blob of data that's stored in the world header.  Any further context information would need to be distilled and mapped somehow, and there are probably better ways to organize your banner collection in the game.  I'm still considering some better ways to present it, but I figured I might as well start off with a simple reasonably human readable format.

(I've noticed a couple minor issues that I need to tweak, will fix shortly.)

**Comment by TheHoodedTeddy13** [comment]
Oh, I thought it was editable, if it's just to represent, then that's fine, Though I would make every other row a lighter shade, so it's easier to read across, and maybe have 2 columns, one for the name, one for the number.  Otherwise it may as well be popping it up in notepad.

**Comment by SBlogic** [comment]
It's just a simple textbox control, and I'm not sure if ledger lines are possible in that context, but I'll look into it.  As it is now, the output is practical for loading into another program so it can be rearranged and sorted as the user sees fit to do.

Re: the Arapaima kills, this is my world I carried over from 1.2.  I have an ocean coin farm, and I was doing some testing to make sure it was still functional (I had some slight tuning to do on it, but otherwise it works about the same).

**Comment by SBlogic** [comment]
Pulled over from #601, I agree it's redundant and should be refactored to use the existing tile data for chests.

**Comment by sdq11111** [comment]
@SBlogic Redundancy of chests in setting.xml is removed.

**Comment by CyberZHG** [comment]
@SBlogic Redundency of chests in setting.xml is removed.

**Comment by enigmaquip** [comment]
@CyberZHG I like what you've added, don't forget that dressers are now chests as well

**Comment by TheHoodedTeddy13** [comment]
They are?! (Goes to check.)

**Comment by CyberZHG** [comment]
@enigmaquip Not only me forgot the dressers, most of the codes didn't check the dresser type.
So I added two functions to `Tile`: `IsChest(int)` and `IsSign(int)`. And I changed the hard-coded checkings of chests and signs appeared in the code except that in the plugin: `Remove all chests`, `Unlock all chests`, `Remove all unlocked chests`. I think it is more intuitive to restrict the meaning of chest in these plugins.

**Pull request merged**
