### PR TITLE
Fix Bestiary Loading.

### PR DESCRIPTION
**Pull request by jerry123z**

### CODE REVIEW

**Comment by jerry123z** [comment]
This should fix #1194 and #1192.

**Comment by jerry123z** [comment]
Attempting to save a world with this commit doesn't crash with the CreativePowers error. I'm not sure if the issue is actually fixed. Those should be tested further.

**Comment by jerry123z** [comment]
I should note that the tallies tab in the UI remains blank

**Comment by finleyuk8** [comment]
what file do i use this code in?

**Comment by finleyuk8** [comment]
I am confused as how to use this? in which file do I use this changed code in?

**Comment by jerry123z** [comment]
@finleyuk8 you can just clone [my fork] (https://github.com/jerry123z/Terraria-Map-Editor)
If you want to edit the files yourself the file is /TEditXna/Terraria/Bestiary.cs

**Comment by finleyuk8** [comment]
I downloaded your forkbut i now have no idea, what to do with it, sorry if i'm sounding dumb, i've never reallly done anything like this

**Comment by jerry123z** [comment]
Download the Visual Studio Installer https://visualstudio.microsoft.com/

When you open the installer you want to get VS Community 2019,  make sure you have the .NET Desktop workload selected.

Once you have VS 2019 you want to open the .sln file and from there you can build the file or run in debug mode.

**Comment by BinaryConstruct** [comment]
Sorry, I had made these changes without checking for a PR. Thank you for the changes.

**Comment by finleyuk8** [comment]
I think I'll just wait for Beta 3 then, hopefully it comes in the next few days, thanks anyway

**Comment by finleyuk8** [comment]
is the SLN file you mentioned TEditNoInstaller.sln ?

**Pull request closed without merging**
